url: "https://konggadinata.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://konggadinata.github.io" # the subpath of your site, e.g. /blog
title: "Kelvin Onggadinata" # the name of your site, e.g. ACME Corp.
description: "Personal website"
